# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
reviews:
  auto_review:
    enabled: true
    drafts: false
    base_branches: ["main", "master"]
chat:
  auto_reply: true 